version: 2.1
orbs:
  node: circleci/node@4.0.1
jobs:
  build:
    docket:
      - image: circleci/node:10.15.3

    steps:
      - checkout
      - run: npm start
      - run: npm test
# workflows:
#   node-tests:
#     jobs:
#       - node/test:
#         version: 10.15.3
